// Generated by tools/build-contract.js. Do not edit by hand.
//
// Every selector here is keccak256 of the signature beside it, computed at
// build time and checked against published vectors first. None of it is
// copied from another project, which is why this file exists: the page used
// to send tick(uint256,uint8) at a contract whose function is step().
//
// The layout below is the ST-8's. A chip built on a later generation
// reports its own through spec(), which is why the contracts stopped
// hardcoding these and the page reads them from here only as a default.
window.ST8_ABI = {
  step: "0x3a1cde75",   // step(uint256)
  snapshot: "0x9711715a",   // snapshot()
  registers: "0xa0d3d084",   // registers()
  state: "0xc19d93fb",   // state()
  ram: "0x1fc4b242",   // ram(uint256)
  program: "0xc860ebc6",   // program()
  spec: "0xf448c9bc",   // spec()
  launch: "0x73a28fbd",   // launch(bytes,(string,string,string,string,(string,string,string,string,string),address,uint16,bool,bytes32,bytes32),uint256,address)
  tokenURI: "0xc87b56dd",   // tokenURI(uint256)
  records: "0x34461067",   // records(uint256)
  idOfChip: "0x8bc56e80",   // idOfChip(address)
  totalChips: "0x2ddbd13a",   // total()
  launchFee: "0xcf3cf573",   // launchFee()
  canLaunch: "0x58373f04",   // canLaunch(address)
  previewLaunchEconomics: "0xf718b78c",   // previewLaunchEconomics(uint256,address)
  launchConfigCount: "0xae72d871",   // launchConfigCount()

  steppedTopic: "0xed5cd9f6d6997b24d4fe100f731d98974dc1b7603f1cf2982be98d1826c9ef48",
  // keccak256 of Stepped(address,uint40,uint256,uint256)

  // Where each field sits inside the packed state word. Contiguous, so the
  // page reads them the same way the contract does: a shift and a mask.
  stateBits: 167,
  pc: { shift: 128, width: 10 },
  out: { shift: 138, width: 8 },
  cf: 146, zf: 147, halt: 148,
};
